name: Run Auto Tests

on:  
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2 

      - name: Backend
        run: |
          git clone https://github.com/bondarenkokate73/simbirsoft_sdet_project.git
          cd simbirsoft_sdet_project
          sudo make run

      - name: Wait for backend to be ready
        run: |
         curl --retry 10 --retry-delay 5 --max-time 60 --silent http://localhost:8000/health || exit 1
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests in parallel with pytest
        run: pytest -n auto

      - name: Shut down Docker containers
        run: |
          docker-compose down 
